### PR TITLE
Migrate to CircleCI 2.0

### PR DESCRIPTION
**Pull request by serima**
Speed up CircleCI runs.

### CODE REVIEW

**Comment by ydnar** [comment]
Thanks! LGTM—just requested a review from @cee-dub who looks after our CI configs.

**Comment by serima** [comment]
@cee-dub Thanks for reviewing. I'll fix below
- use official golang image
- switch JUnit formatter from current fork to `jstemmer/go-junit-report`
- revert 1.0 config

**Comment by cee-dub** [comment]
@serima thank you!

**Comment by serima** [comment]
@cee-dub Fixed! Please re-review.

**Pull request merged**
