### PR TITLE
WIP: Parser implementation for ICANN specified WHOIS data

### PR DESCRIPTION
**Pull request by yookoala**
* Rebase "parser" branch on latest master.
* Add Record field definitions.
* Add Parser interface and DefaultParser for [ICANN specified WHOIS data format](https://www.icann.org/resources/pages/approved-with-specs-2013-09-17-en#whois) in their 2013 Registrar Accreditation Agreement.

### CODE REVIEW

**Comment by ydnar** [comment]
Wow, thanks! Are you using this code anywhere?

**Comment by yookoala** [comment]
@ydnar: Not yet.

Also, this is still work in progress. I'm working on a mux to properly route to different Parser.

**Comment by ydnar** [comment]
OK.

Maybe we should update zonedb.org with metadata on whois format?

**Comment by yookoala** [comment]
Maybe. Depends on how they are stored.

I don't think tld and whois format is a 1-to-1 relation. If we're just talking about thick WHOIS entries, then maybe it works. But some popular tld (e.g. .COM, .NET) are running the thin WHOIS entries model. The format of the WHOIS response would also depends on the registrar.

So a complete set of information would include both tld and specific registrar format.

**Pull request closed without merging**
